# Generated by Django 5.2.18 on 2026-10-09 08:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('FINISHED', '成品'), ('SEMI', '半成品'), ('RAW', '原料')], max_length=8)),
                ('unit', models.CharField(max_length=32)),
                ('traceability_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('output_qty', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '生效'), ('RETIRED', '停用')], default='DRAFT', max_length=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.bom')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='catalog.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bom', 'component'), name='bom_component_unique'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bom_qty_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='bom_item_version'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('item',), name='bom_one_active'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.CheckConstraint(condition=models.Q(('output_qty__gt', 0)), name='bom_output_positive'),
        ),
    ]
