# Generated by Django 5.2.18 on 2026-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bom_revision_item_revision_alter_bom_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allergens',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='product_standard',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_condition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
