# Generated by Django 5.2.18 on 2026-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
