import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { expect, test } from '@playwright/test'

test('cross-order scheduling, manual sequence, reporting and live sales progress', async ({ page, context }) => {
  const docker = process.env.E2E_BASE_URL?.includes(':8080')
  const root = fileURLToPath(new URL('../../', import.meta.url))
  const credentials = JSON.parse(readFileSync(new URL(`../../.tools/access.${docker ? 'docker' : 'local'}.json`, import.meta.url), 'utf8'))
  const prefix = `E2E-CROSS-${Date.now()}`
  await page.goto('/')
  await page.locator('form.login input').nth(0).fill(credentials.username)
  await page.locator('form.login input').nth(1).fill(credentials.password)
  await page.locator('form.login').getByRole('button', { name: '登录', exact: true }).click()
  await page.evaluate(() => { const input = document.querySelector<HTMLInputElement>('input[type="password"]'); if (input) input.value = '' })
  await expect(page.getByRole('heading', { name: '物料管理' })).toBeVisible()
  async function api(path: string, body: unknown, method = 'POST') {
    const result = await page.evaluate(async ({ path, body, method }) => {
      const session = await (await fetch('/api/v1/auth/session/')).json()
      const response = await fetch(`/api/v1/${path}`, { method, headers: { 'Content-Type': 'application/json', 'X-CSRFToken': session.csrfToken }, body: JSON.stringify(body) })
      return { status: response.status, data: await response.json() }
    }, { path, body, method })
    expect(result.status).toBeLessThan(300)
    return result.data
  }
  try {
    const raw = await api('items/', { code: prefix + '-RAW', name: '测试原料', kind: 'RAW', unit: 'kg' })
    const item = await api('items/', { code: prefix + '-PRODUCT', name: prefix + ' 调味酱', kind: 'SEMI', unit: 'kg' })
    const bom = await api('boms/', { item: item.id, output_qty: '1', lines: [{ component: raw.id, quantity: '2' }] })
    await api(`boms/${bom.id}/publish/`, {})
    const first = await api('sales-orders/', { number: prefix + '-A', customer_name: '测试客户甲', priority: 1, lines: [{ item: item.id, quantity: '5' }] })
    const second = await api('sales-orders/', { number: prefix + '-B', customer_name: '测试客户乙', priority: 3, lines: [{ item: item.id, quantity: '4' }] })
    const other = await api('items/', { code: prefix + '-OTHER', name: prefix + ' 撒料', kind: 'FINISHED', unit: '袋' })
    const otherBom = await api('boms/', { item: other.id, output_qty: '1', lines: [{ component: raw.id, quantity: '1' }] })
    await api(`boms/${otherBom.id}/publish/`, {})
    const third = await api('sales-orders/', { number: prefix + '-C', customer_name: '测试客户丙', priority: 2, lines: [{ item: other.id, quantity: '2' }] })
    await api(`sales-orders/${first.id}/confirm/`, {})
    await api(`sales-orders/${second.id}/confirm/`, {})
    await api(`sales-orders/${third.id}/confirm/`, {})
    await page.getByRole('tab', { name: '排产与生产', exact: true }).click()
    await expect(page.getByRole('heading', { name: '生成跨订单生产建议' })).toBeVisible()
    await page.locator('.planner-input .el-input input').fill(prefix + ' 跨单计划')
    await page.locator('.planner-input .el-select').click()
    await page.getByRole('option', { name: `${first.number} · 测试客户甲 · P1`, exact: true }).click()
    await page.getByRole('option', { name: `${second.number} · 测试客户乙 · P3`, exact: true }).click()
    await page.getByRole('option', { name: `${third.number} · 测试客户丙 · P2`, exact: true }).click()
    await page.getByRole('heading', { name: '生成跨订单生产建议' }).click()
    await page.getByRole('button', { name: '生成建议', exact: true }).click()
    const planRow = page.getByRole('row').filter({ hasText: prefix + ' 跨单计划' })
    await expect(planRow).toBeVisible()
    await planRow.getByRole('button', { name: '查看 / 调整', exact: true }).click()
    const planDialog = page.getByRole('dialog', { name: prefix + ' 跨单计划', exact: true })
    await expect(planDialog.getByText('9.000000 kg · P1')).toBeVisible()
    await planDialog.getByRole('spinbutton').nth(0).fill('2')
    await planDialog.getByRole('spinbutton').nth(1).fill('1')
    await planDialog.getByPlaceholder('覆盖建议顺序时必填').nth(0).fill('演示人工优先安排撒料')
    await planDialog.getByPlaceholder('覆盖建议顺序时必填').nth(1).fill('演示人工优先安排撒料')
    const adjusted = page.waitForResponse(response => response.url().includes('/plans/') && response.request().method() === 'PATCH')
    await planDialog.getByRole('button', { name: '保存调整', exact: true }).click()
    expect((await adjusted).status()).toBe(200)
    await planDialog.getByRole('button', { name: '发布已保存方案', exact: true }).click()
    await page.getByRole('button', { name: '确定', exact: true }).click()
    const queueDialog = page.getByRole('dialog', { name: '全局未开工队列 · 插入建议', exact: true })
    await expect(queueDialog).toBeVisible()
    await queueDialog.getByRole('button', { name: '暂不调整', exact: true }).click()
    await page.getByRole('tab', { name: '生产安排与报工', exact: true }).click()
    const productionRow = page.getByRole('row').filter({ hasText: item.name })
    await expect(productionRow.getByText('待开工', { exact: true })).toBeVisible()

    const observer = await context.newPage()
    await observer.goto('/')
    await observer.getByRole('tab', { name: '销售单', exact: true }).click()
    const saleA = observer.getByRole('row').filter({ hasText: first.number })
    const saleB = observer.getByRole('row').filter({ hasText: second.number })
    await expect(saleA.getByText('已确认', { exact: true })).toBeVisible()
    await productionRow.getByRole('button', { name: '调演示进度', exact: true }).click()
    const demoDialog = page.getByRole('dialog', { name: '调整演示进度', exact: true })
    await demoDialog.getByRole('spinbutton').fill('70', { timeout: 5000 })
    await demoDialog.getByRole('button', { name: '保存演示进度', exact: true }).click({ timeout: 5000 })
    await expect(productionRow.getByText('70%', { exact: true })).toBeVisible()
    await expect(saleA.getByText('99.99%', { exact: true })).toBeVisible({ timeout: 3500 })
    await expect(saleB.getByText('32.5%', { exact: true })).toBeVisible({ timeout: 3500 })
    await expect(saleA.getByText('已确认', { exact: true })).toBeVisible()
    await expect(saleA.getByText('含演示进度 · 真实 0%', { exact: true })).toBeVisible()
    await expect(productionRow.getByText('待开工', { exact: true })).toBeVisible()
    await productionRow.getByRole('button', { name: '开工', exact: true }).click()
    await productionRow.getByRole('button', { name: '报工', exact: true }).click()
    const reportDialog = page.getByRole('dialog', { name: item.name + ' · 合格产量报工', exact: true })
    await reportDialog.locator('input').nth(0).fill('6')
    await reportDialog.getByRole('button', { name: '提交报工', exact: true }).click()
    await expect(saleA.getByText('已完成', { exact: true })).toBeVisible({ timeout: 3500 })
    await expect(saleB.getByText('25%', { exact: true })).toBeVisible({ timeout: 3500 })
    await expect(productionRow.getByText('演示进度 · 真实 0%', { exact: true })).not.toBeVisible()
    await expect(saleB.getByText('含演示进度', { exact: false })).not.toBeVisible()
    await productionRow.getByRole('button', { name: '详情', exact: true }).click()
    const details = page.getByRole('dialog').filter({ hasText: '来源与回分（等级在发布时冻结）' })
    await expect(details.getByRole('row').filter({ hasText: first.number }).getByRole('cell', { name: '5.000000', exact: true }).last()).toBeVisible()
    await expect(details.getByRole('row').filter({ hasText: second.number }).getByRole('cell', { name: '1.000000', exact: true })).toBeVisible()
    await observer.close()
  } finally {
    if (docker) execFileSync('docker', ['exec', '--workdir', '/app/backend', 'neo-aps', 'python', 'manage.py', 'cleanup_e2e', '--prefix', prefix], { cwd: root })
    else execFileSync(fileURLToPath(new URL('../../.venv/Scripts/python.exe', import.meta.url)), ['backend/manage.py', 'cleanup_e2e', '--prefix', prefix], { cwd: root })
  }
})
