# Generated by Django 5.2.18 on 2026-10-09 09:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_bom_revision_item_revision_alter_bom_version'),
        ('sales', '0002_salesorder_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='排产方案', max_length=120)),
                ('status', models.CharField(default='DRAFT', max_length=12)),
                ('inputs', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='production.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('task_key', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('completed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=12)),
                ('snapshot', models.JSONField(default=dict)),
                ('materials', models.JSONField(default=list)),
                ('target_start', models.DateField(blank=True, null=True)),
                ('target_end', models.DateField(blank=True, null=True)),
                ('line_label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.batch')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.bom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.item')),
            ],
            options={
                'ordering': ['sequence', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('path', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fulfilled_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('priority', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('source', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='production.allocation')),
                ('sales_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.salesline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='production.productionorder')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('request_key', models.CharField(max_length=100, unique=True)),
                ('batch_code', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='production.productionorder')),
                ('reversal_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='production.report')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReportAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.allocation')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='production.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('batch', 'task_key'), name='production_task_unique'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='production_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('completed_qty__gte', 0), ('completed_qty__lte', models.F('quantity'))), name='production_completed_range'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='production_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('order', 'rank'), name='allocation_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='allocation_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 0), ('fulfilled_qty__lte', models.F('quantity'))), name='allocation_fulfilled_range'),
        ),
    ]
