# Generated by Django 5.2.18 on 2026-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_allergens_item_product_standard_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='demo_progress_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('demo_progress_percent__isnull', True), models.Q(('demo_progress_percent__gte', 0), ('demo_progress_percent__lt', 100)), _connector='OR'), name='production_demo_progress_range'),
        ),
    ]
